site_name: Grocery Goose
site_url: https://usegrocerygoose.com
site_description: Documentation for the Grocery Goose application
# repo_url: https://github.com/grocerygoose/grocerygooose-site
# repo_name: grocery-gooose

theme:
  name: material
  logo: assets/grocery-goose.svg
  favicon: assets/grocery-goose.png
  features:
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    primary: orange
    accent: orange

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - mermaid2

nav:
  - Home: index.md
  - About: about/about.md
  - Roadmap: about/roadmap.md
  - Contact: contact.md

extra_css:
  - stylesheets/signup.css
  - stylesheets/extra.css

extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js

extra:
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:support@usegrocerygoose.com
    # - icon: fontawesome/brands/twitter
    #   link: https://twitter.com/grocerygoose
    # - icon: fontawesome/brands/instagram
    #   link: https://instagram.com/grocerygoose
  generator: false
